config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  get '2015' => 'events#archiveIndex'

  resources :blogs,  :path => 'news' do
  	collection do
  		get :tag
  	end
  end

  resources :events do
    collection do
      get :tag
    end
  end

  resources :categories

  resources :pages

  get 'locations' => 'venues#index'

  resources :authors, only: :show

	#Casein routes
	namespace :casein do
		resources :embeds
		resources :authors
		resources :tickets
		resources :pages
		resources :venues
		resources :blogs
		resources :categories
		resources :events
	end

  root 'pages#index'
  get 'about' => 'pages#about'
  get 'styleguide' => 'pages#styleguide'
end

app/controllers/casein/authors_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class AuthorsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Authors'
  		@authors = Author.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View author'
      @author = Author.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new author'
    	@author = Author.new
    end

    def create
      @author = Author.new author_params
    
      if @author.save
        flash[:notice] = 'Author created'
        redirect_to casein_authors_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new author'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update author'
      
      @author = Author.find params[:id]
    
      if @author.update_attributes author_params
        flash[:notice] = 'Author has been updated'
        redirect_to casein_authors_path
      else
        flash.now[:warning] = 'There were problems when trying to update this author'
        render :action => :show
      end
    end
 
    def destroy
      @author = Author.find params[:id]

      @author.destroy
      flash[:notice] = 'Author has been deleted'
      redirect_to casein_authors_path
    end
  
    private
      
      def author_params
        params.require(:author).permit(:name)
      end

  end
end

app/controllers/casein/blogs_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class BlogsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Blogs'
  		@blogs = Blog.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View blog'
      @blog = Blog.friendly.find_by_slug! params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new blog'
    	@blog = Blog.new
    end

    def create
      @blog = Blog.new blog_params
    
      if @blog.save
        flash[:notice] = 'Blog created'
        redirect_to casein_blogs_path
        expire_page  '/news'
        expire_page '/index.html'
      else
        flash.now[:warning] = 'There were problems when trying to create a new blog'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update blog'
      
      @blog = Blog.friendly.find_by_slug! params[:id]
    
      if @blog.update_attributes blog_params
        flash[:notice] = 'Blog has been updated'
        expire_page  '/news'
        expire_page  "/news/#{params[:id]}"
        expire_page '/index.html'
        redirect_to casein_blogs_path
      else
        flash.now[:warning] = 'There were problems when trying to update this blog'
        render :action => :show
      end
    end
 
    def destroy
      @blog = Blog.friendly.find_by_slug! params[:id]

      @blog.destroy
      expire_page  '/news'
      expire_page  "/news/#{params[:id]}"
      expire_page '/index.html'
      flash[:notice] = 'Blog has been deleted'
      redirect_to casein_blogs_path
    end
  
    private
      
      def blog_params
        params.require(:blog).permit(:title, :body, :category_id, :author_id, :published, :hero, :tag_list, :published_at)
      end

  end
end

app/controllers/casein/categories_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class CategoriesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Categories'
  		@categories = Category.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View category'
      @category = Category.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new category'
    	@category = Category.new
    end

    def create
      @category = Category.new category_params
    
      if @category.save
        flash[:notice] = 'Category created'
        redirect_to casein_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new category'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update category'
      
      @category = Category.find params[:id]
    
      if @category.update_attributes category_params
        flash[:notice] = 'Category has been updated'
        redirect_to casein_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this category'
        render :action => :show
      end
    end
 
    def destroy
      @category = Category.find params[:id]

      @category.destroy
      flash[:notice] = 'Category has been deleted'
      redirect_to casein_categories_path
    end
  
    private
      
      def category_params
        params.require(:category).permit(:name)
      end

  end
end

app/controllers/casein/embeds_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class EmbedsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Embeds'
  		@embeds = Embed.order(sort_order(:created_at)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View embed'
      @embed = Embed.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new embed'
    	@embed = Embed.new
    end

    def create
      @embed = Embed.new embed_params
    
      if @embed.save
        flash[:notice] = 'Embed created'
        expire_page '/index.html'
        redirect_to casein_embeds_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new embed'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update embed'
      
      @embed = Embed.find params[:id]
    
      if @embed.update_attributes embed_params
        flash[:notice] = 'Embed has been updated'
        expire_page '/index.html'
        redirect_to casein_embeds_path
      else
        flash.now[:warning] = 'There were problems when trying to update this embed'
        render :action => :show
      end
    end
 
    def destroy
      @embed = Embed.find params[:id]

      @embed.destroy
      flash[:notice] = 'Embed has been deleted'
      redirect_to casein_embeds_path
    end
  
    private
      
      def embed_params
        params.require(:embed).permit(:source)
      end

  end
end

app/controllers/casein/events_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class EventsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Events'
  		@events = Event.includes(:category).order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View event'
      @event = Event.friendly.find_by_slug! params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new event'
    	@event = Event.new
    end

    def create
      @event = Event.new event_params
    
      if @event.save
        flash[:notice] = 'Event created'
        expire_page  '/events'
        expire_page '/index.html'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new event'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update event'
      
      @event = Event.friendly.find_by_slug! params[:id]
    
      if @event.update_attributes event_params
        flash[:notice] = 'Event has been updated'
        expire_page  '/events'
        expire_page  "/events/#{params[:id]}"
        expire_page '/index.html'

        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to update this event'
        render :action => :show
      end
    end
 
    def destroy
      @event = Event.friendly.find_by_slug! params[:id]

      @event.destroy
      expire_page  '/events'
      expire_page '/index.html'
      expire_page  "/events/#{params[:id]}"
      flash[:notice] = 'Event has been deleted'
      redirect_to casein_events_path
    end
  
    private
      
      def event_params
        params.require(:event).permit(:name,
          :venue_id,
          :description,
          :details,
          :start_at,
          :end_at,
          :price,
          :featured,
          :all_day,
          :img1,
          :shortimg1,
          :category_id,
          :tag_list,
          :publish_at,
          tickets_attributes: [:id, :name, :url, :_destroy],
        )
      end

  end
end

app/controllers/casein/pages_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class PagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Pages'
  		@pages = Page.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View page'
      @page = Page.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new page'
    	@page = Page.new
    end

    def create
      @page = Page.new page_params
    
      if @page.save
        flash[:notice] = 'Page created'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new page'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update page'
      
      @page = Page.find params[:id]
    
      if @page.update_attributes page_params
        flash[:notice] = 'Page has been updated'
        expire_page  '/about.html'
        redirect_to casein_pages_path
      else
        flash.now[:warning] = 'There were problems when trying to update this page'
        render :action => :show
      end
    end
 
    def destroy
      @page = Page.find params[:id]

      @page.destroy
      flash[:notice] = 'Page has been deleted'
      redirect_to casein_pages_path
    end
  
    private
      
      def page_params
        params.require(:page).permit(:title, :body)
      end

  end
end

app/controllers/casein/tickets_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class TicketsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Tickets'
  		@tickets = Ticket.order(sort_order(:url)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View ticket'
      @ticket = Ticket.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new ticket'
    	@ticket = Ticket.new
    end

    def create
      @ticket = Ticket.new ticket_params
    
      if @ticket.save
        flash[:notice] = 'Ticket created'
        redirect_to casein_tickets_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new ticket'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update ticket'
      
      @ticket = Ticket.find params[:id]
    
      if @ticket.update_attributes ticket_params
        flash[:notice] = 'Ticket has been updated'
        redirect_to casein_tickets_path
      else
        flash.now[:warning] = 'There were problems when trying to update this ticket'
        render :action => :show
      end
    end
 
    def destroy
      @ticket = Ticket.find params[:id]

      @ticket.destroy
      flash[:notice] = 'Ticket has been deleted'
      redirect_to casein_tickets_path
    end
  
    private
      
      def ticket_params
        params.require(:ticket).permit(:url, :name)
      end

  end
end

app/controllers/casein/venues_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class VenuesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Venues'
  		@venues = Venue.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View venue'
      @venue = Venue.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new venue'
    	@venue = Venue.new
    end

    def create
      @venue = Venue.new venue_params
    
      if @venue.save
        flash[:notice] = 'Venue created'
        expire_page  '/locations'
        redirect_to casein_venues_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new venue'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update venue'
      
      @venue = Venue.find params[:id]
    
      if @venue.update_attributes venue_params
        flash[:notice] = 'Venue has been updated'
        expire_page  '/locations'
        redirect_to casein_venues_path
      else
        flash.now[:warning] = 'There were problems when trying to update this venue'
        render :action => :show
      end
    end
 
    def destroy
      @venue = Venue.find params[:id]

      @venue.destroy
      flash[:notice] = 'Venue has been deleted'
      redirect_to casein_venues_path
    end
  
    private
      
      def venue_params
        params.require(:venue).permit(:name, :location, :details)
      end

  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Convergence'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/convergence.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.convergence-london.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@convergence-london.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :events, :action => :index
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom ckeditor/init nested_form_fields]
    end
    
  end
end

app/helpers/events_helper.rb
module EventsHelper

	def eventImage(event)
		if event.hasImage
			return event.img1
		else
			return asset_path "dots.png"
		end
	end
end

app/views/casein/events/_form.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<div class="row">
	<div class="col-lg-6">
		<%= casein_select f, f.object, :category_id, Category.order(:name).collect {|c| [c.name.titlecase, c.id]},
			{:include_blank => '-- None --', :casein_label => "Choose a category"} %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-6">
		<%= casein_select f, f.object, :venue_id, Venue.order(:name).collect {|c| [c.name.titlecase, c.id]},
			{:include_blank => '-- None --', :casein_label => "Choose a venue"} %>
	</div>

</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_field f, f.object, :details %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<%= cktext_area :event, :description, :cols => 40, :ckeditor => {:height => '800px', :uiColor => '#f1f1f1',:toolbar => 'convergence', :extraAllowedContent => 'iframe[*]'} %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_datetime_select f, f.object, :start_at %>
	</div>
	<div class="col-lg-6">
		<%= casein_datetime_select f, f.object, :end_at %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :price, { :casein_label => "Price (£)"} %>
	</div>
	<div class="col-lg-6">
		<%= casein_check_box f, f.object, :featured, { :casein_label => "Featured in carousel at top of homepage?"}%>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_check_box f, f.object, :all_day, { :casein_label => "All-day event?"} %>
	</div>
	<div class="col-lg-6">
		
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_file_field f, f.object, "event", :img1 , { :casein_label => "Event image (one image only)"}%>
	</div>
	<div class="col-lg-6">
		<label class="control-label" for="event_img1">Currently loaded image:</label>
		<%= if @event.img1? then image_tag(@event.img1, width: '300') else content_tag(:span, "No image yet") end %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_file_field f, f.object, "event", :shortimg1 , { :casein_label => "Short event image (one image only)"}%>
	</div>
	<div class="col-lg-6">
		<label class="control-label" for="event_shortimg1">Currently loaded image:</label>
		<%= if @event.shortimg1? then image_tag(@event.shortimg1, width: '300') else content_tag(:span, "No image yet") end %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :tag_list %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_datetime_select f, f.object, :publish_at %>
	</div>
</div>

	<h2>Ticket links</h2>
	<%= f.nested_fields_for :tickets do |ff| %>
	<div class="row">
		<div class="col-lg-6">
			<div class="form-group">
				<label class="control-label" for="event_name">Name</label>
				<div class="well">
					<%= ff.text_field :name %>
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="form-group">
				<label class="control-label" for="event_name">URL</label>
				<div class="well">
					<%= ff.text_field :url %><span style="margin-left: 20px"><%= ff.remove_nested_fields_link "delete this link" %></span>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<%= f.add_nested_fields_link :tickets, "Add another ticket link" %>
	
	<br />
	<br />
	<br />

app/views/casein/events/_table.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Venue", :venue_id %></th>
			<th><%= casein_sort_link "Start time", :start_at %></th>
			<th><%= casein_sort_link "End time", :end_at %></th>
			<th><%= casein_sort_link "Price", :price %></th>
			<th><%= casein_sort_link "Featured", :featured %></th>
			<th><%= casein_sort_link "All day", :all_day %></th>
			<th><%= casein_sort_link "Category", :category %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% events.each do |event| %>

		<tr>
			<td><%= casein_table_cell_link event.name, casein_event_path(event) %></td>
			<td><% if event.venue %><%= casein_table_cell_link event.venue.name.html_safe, casein_event_path(event) %><% end %></td>
			<td><%= casein_table_cell_link event.start_at.strftime("%H:%M %^h %d"), casein_event_path(event) %></td>
			<td><%= casein_table_cell_link event.end_at.strftime("%H:%M %^h %d"), casein_event_path(event) %></td>
			<td><%= casein_table_cell_link event.price, casein_event_path(event) %></td>
			<td><%= casein_table_cell_link event.featured, casein_event_path(event) %></td>
			<td><%= casein_table_cell_link event.all_day, casein_event_path(event) %></td>
			<td>
				<% if event.category %>
				<%= casein_table_cell_link event.category.name, casein_event_path(event) %>
				<% end %>
			</td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_event_path(event), :method => :delete, :data => { :confirm => "Are you sure you want to delete this event?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/events/index.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Events<%= casein_pagination_details @events %></h2>

<%= render :partial => 'casein/events/table', :locals => { :events => @events } %>

<div class="text-center">
	<%= will_paginate @events %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new event".html_safe, new_casein_event_path %></li>

<% end %>

app/views/casein/events/new.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Add a new event</h2>

<%= form_for @event, :url => casein_events_path, :html => {:multipart => true} do |f| %>
	
	<%= render :partial => 'casein/events/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_events_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new event", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_events_path %></li>
<% end %>

app/views/casein/events/show.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>View event</h2>

<%= form_for @event, :url => casein_event_path(@event), :html => { :multipart => true } do |f| %>

	<%= render :partial => 'casein/events/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_events_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_events_path %></li>
<% end %>